<?php
/**
 * Load a song collection generated by build_collection.py into the
 * database. Connects through the app's own DB config, exactly like
 * database/translations/apply.php (the server's mysql CLI is broken).
 *
 * Run on the server:
 *   php database/collections/apply_collection.php <data.json>           # apply
 *   php database/collections/apply_collection.php --check <data.json>   # parse + stats only
 *
 * The data file carries list_name and per-song texts keyed by content-
 * language code; codes are resolved to TEXT<col_suffix> columns through
 * the `languages` table (never hardcoded). Re-runnable: an existing
 * collection with the same LIST_NAME keeps its LIST_ID (and image
 * groups); its song rows are replaced wholesale in one transaction.
 * A new collection gets MAX(LIST_ID)+1 and the default image groups
 * (SongImages::ensureDefaults). Visibility per group is NOT touched —
 * an admin enables the collection in settings (available_lists).
 */

$check = false;
$file  = null;
foreach (array_slice($argv, 1) as $a) {
    if ($a === '--check') { $check = true; continue; }
    $file = $a;
}
if ($file === null) {
    fwrite(STDERR, "usage: php apply_collection.php [--check] <data.json>\n");
    exit(2);
}
if (!is_file($file) && is_file(__DIR__ . '/' . $file)) {
    $file = __DIR__ . '/' . $file;
}
$json = json_decode(file_get_contents($file), true);
if (!$json || empty($json['songs']) || empty($json['list_name'])) {
    fwrite(STDERR, "{$file}: parse failed or empty\n");
    exit(1);
}
$listName = $json['list_name'];
$songs    = $json['songs'];
$verses   = 0;
$langs    = [];
foreach ($songs as $s) {
    if (!isset($s['num'], $s['name']) || empty($s['texts']) || !is_array($s['texts'])) {
        fwrite(STDERR, "bad song entry: " . json_encode($s, JSON_UNESCAPED_UNICODE) . "\n");
        exit(1);
    }
    foreach ($s['texts'] as $lg => $t) {
        if ($t === '') {
            fwrite(STDERR, "song {$s['num']}: empty text for '{$lg}'\n");
            exit(1);
        }
        $langs[$lg] = ($langs[$lg] ?? 0) + 1;
        $verses += substr_count($t, "\r\n") + 1;
    }
}
printf("%s: %d songs, langs %s, %d verse lines\n",
    $listName, count($songs), json_encode($langs), $verses);
if ($check) {
    echo "--check: parsed only, nothing executed.\n";
    exit(0);
}

chdir(__DIR__ . '/../../public');
include '../app/Info.php';
include '../app/Database.php';
include '../app/SongImages.php';
Info::set('config', include '../app/config.php');
$db = new Database();
Info::set('db', $db);
$dbh = $db->db_handle();
Info::set('dbh', $dbh);

// Content-language code -> TEXT column, from the registry ('' suffix = TEXT).
$cols = [];
foreach ($db->select("SELECT code, col_suffix FROM languages") as $r) {
    $cols[$r['code']] = 'TEXT' . $r['col_suffix'];
}
foreach (array_keys($langs) as $lg) {
    if (!isset($cols[$lg])) {
        fwrite(STDERR, "unknown content language '{$lg}' (languages table has: " . implode(', ', array_keys($cols)) . ")\n");
        exit(1);
    }
}
$useLangs = array_keys($langs);
$colList  = array_map(function ($lg) use ($cols) { return $cols[$lg]; }, $useLangs);

$nameEsc = mysqli_real_escape_string($dbh, $listName);
$row = $db->get("SELECT LIST_ID FROM list_names WHERE LIST_NAME = '{$nameEsc}'");
if ($row) {
    $listId = (int)$row['LIST_ID'];
    $old = (int)$db->getValue("SELECT COUNT(*) FROM song_list WHERE LISTID = {$listId}");
    echo "collection exists: LIST_ID={$listId}, replacing its {$old} songs\n";
} else {
    $listId = (int)$db->getValue("SELECT MAX(LIST_ID) FROM list_names") + 1;
    // ADDEDBY is informational only (never read back); 1 = the system owner's group.
    $db->exec("INSERT INTO list_names (LIST_ID, LIST_NAME, ADDEDBY) VALUES ({$listId}, '{$nameEsc}', 1)");
    echo "created collection: LIST_ID={$listId}\n";
}
SongImages::ensureDefaults($listId);

mysqli_query($dbh, 'START TRANSACTION');
// Direct mysqli_query everywhere below: Database::exec() swallows errors
// (always returns true), and a failed statement must roll the batch back.
if (!mysqli_query($dbh, "DELETE FROM song_list WHERE LISTID = {$listId}")) {
    fwrite(STDERR, "delete failed: " . mysqli_error($dbh) . "\n");
    mysqli_query($dbh, 'ROLLBACK');
    exit(1);
}
$vals = [];
foreach ($songs as $s) {
    $parts = [
        (string)$listId,
        "'" . mysqli_real_escape_string($dbh, $s['num']) . "'",
        "'" . mysqli_real_escape_string($dbh, $s['name']) . "'",
    ];
    foreach ($useLangs as $lg) {
        $parts[] = isset($s['texts'][$lg])
            ? "'" . mysqli_real_escape_string($dbh, $s['texts'][$lg]) . "'"
            : 'NULL';
    }
    $vals[] = '(' . implode(', ', $parts) . ')';
}
$insCols = 'LISTID, NUM, NAME, ' . implode(', ', $colList);
foreach (array_chunk($vals, 100) as $chunk) {
    if (!mysqli_query($dbh, "INSERT INTO song_list ({$insCols}) VALUES\n" . implode(",\n", $chunk))) {
        fwrite(STDERR, "insert failed: " . mysqli_error($dbh) . "\n");
        mysqli_query($dbh, 'ROLLBACK');
        fwrite(STDERR, "rolled back\n");
        exit(1);
    }
}
mysqli_query($dbh, 'COMMIT');

$cnt = $db->getValue("SELECT COUNT(*) FROM song_list WHERE LISTID = {$listId}");
$grp = $db->getValue("SELECT COUNT(*) FROM song_image_groups WHERE LISTID = {$listId}");
echo "done: LIST_ID={$listId} now holds {$cnt} songs ({$insCols}), {$grp} image groups\n";
foreach ($db->select("SELECT NUM, NAME FROM song_list WHERE LISTID = {$listId} ORDER BY NUM LIMIT 3") as $r) {
    echo "  {$r['NUM']}  {$r['NAME']}\n";
}
