<?php
/**
 * Load the «Tiktai tikėk (Only Believe)» songbook (tiktai_tikek.json,
 * generated by build_tiktai_tikek.py) into the database as a song
 * collection. Connects through the app's own DB config, exactly like
 * database/translations/apply.php (the server's mysql CLI is broken).
 *
 * Run on the server:
 *   php database/collections/apply_tiktai_tikek.php           # apply
 *   php database/collections/apply_tiktai_tikek.php --check   # parse + stats only
 *
 * Re-runnable: an existing collection with the same LIST_NAME keeps its
 * LIST_ID (and image groups); its song rows are replaced wholesale.
 * A new collection gets MAX(LIST_ID)+1 and the default image groups
 * (SongImages::ensureDefaults). Visibility per group is NOT touched —
 * an admin enables the collection in settings (available_lists).
 */

$check = in_array('--check', $argv, true);

$json = json_decode(file_get_contents(__DIR__ . '/tiktai_tikek.json'), true);
if (!$json || empty($json['songs']) || empty($json['list_name'])) {
    fwrite(STDERR, "tiktai_tikek.json: parse failed or empty\n");
    exit(1);
}
$listName = $json['list_name'];
$songs    = $json['songs'];
$verses   = 0;
$chars    = 0;
foreach ($songs as $s) {
    if (!isset($s['num'], $s['name'], $s['text_lt']) || $s['text_lt'] === '') {
        fwrite(STDERR, "bad song entry: " . json_encode($s) . "\n");
        exit(1);
    }
    $verses += substr_count($s['text_lt'], "\r\n") + 1;
    $chars  += strlen($s['text_lt']);
}
printf("%s: %d songs, %d verse lines, %d bytes of text\n", $listName, count($songs), $verses, $chars);
if ($check) {
    echo "--check: parsed only, nothing executed.\n";
    exit(0);
}

chdir(__DIR__ . '/../../public');
include '../app/Info.php';
include '../app/Database.php';
include '../app/SongImages.php';
Info::set('config', include '../app/config.php');
$db = new Database();
Info::set('db', $db);
$dbh = $db->db_handle();
Info::set('dbh', $dbh);

$nameEsc = mysqli_real_escape_string($dbh, $listName);
$row = $db->get("SELECT LIST_ID FROM list_names WHERE LIST_NAME = '{$nameEsc}'");
if ($row) {
    $listId = (int)$row['LIST_ID'];
    $old = (int)$db->getValue("SELECT COUNT(*) FROM song_list WHERE LISTID = {$listId}");
    echo "collection exists: LIST_ID={$listId}, replacing its {$old} songs\n";
} else {
    $listId = (int)$db->getValue("SELECT MAX(LIST_ID) FROM list_names") + 1;
    // ADDEDBY is informational only (never read back); 1 = the system owner's group.
    $db->exec("INSERT INTO list_names (LIST_ID, LIST_NAME, ADDEDBY) VALUES ({$listId}, '{$nameEsc}', 1)");
    echo "created collection: LIST_ID={$listId}\n";
}
SongImages::ensureDefaults($listId);

mysqli_query($dbh, 'START TRANSACTION');
// Direct mysqli_query everywhere below: Database::exec() swallows errors
// (always returns true), and a failed statement must roll the batch back.
if (!mysqli_query($dbh, "DELETE FROM song_list WHERE LISTID = {$listId}")) {
    fwrite(STDERR, "delete failed: " . mysqli_error($dbh) . "\n");
    mysqli_query($dbh, 'ROLLBACK');
    exit(1);
}
$vals = [];
foreach ($songs as $s) {
    $vals[] = sprintf("(%d, '%s', '%s', '%s')",
        $listId,
        mysqli_real_escape_string($dbh, $s['num']),
        mysqli_real_escape_string($dbh, $s['name']),
        mysqli_real_escape_string($dbh, $s['text_lt']));
}
foreach (array_chunk($vals, 100) as $chunk) {
    if (!mysqli_query($dbh, "INSERT INTO song_list (LISTID, NUM, NAME, TEXT_LT) VALUES\n" . implode(",\n", $chunk))) {
        fwrite(STDERR, "insert failed: " . mysqli_error($dbh) . "\n");
        mysqli_query($dbh, 'ROLLBACK');
        fwrite(STDERR, "rolled back\n");
        exit(1);
    }
}
mysqli_query($dbh, 'COMMIT');

$cnt = $db->getValue("SELECT COUNT(*) FROM song_list WHERE LISTID = {$listId}");
$grp = $db->getValue("SELECT COUNT(*) FROM song_image_groups WHERE LISTID = {$listId}");
echo "done: LIST_ID={$listId} now holds {$cnt} songs, {$grp} image groups\n";
foreach ($db->select("SELECT NUM, NAME FROM song_list WHERE LISTID = {$listId} ORDER BY NUM LIMIT 3") as $r) {
    echo "  {$r['NUM']}  {$r['NAME']}\n";
}
