#!/usr/bin/env bash
# Sync the offline Docker copy from production (server.winsys.lv).
#
# Usage:  tools/offline_sync.sh [all|config|db|media]   (default: all)
#   config — generate docker/.env (random DB passwords) and
#            docker/config.container.php (secrets fetched from production)
#   db     — mysqldump production → docker/initdb/00_production.sql.gz
#   media  — public/images, tech_media, sermon_images, sermon_videos (~1.4 GB)
#
# Requires ssh key auth to root@server.winsys.lv (same as tools/deploy.cmd).
# On Windows run from Git Bash, or use tools/offline_sync.cmd.
set -euo pipefail

HOST="root@server.winsys.lv"
REMOTE_APP="/srv/songs"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PART="${1:-all}"

# Escape a value for a single-quoted PHP string literal.
php_esc() { printf "%s" "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"; }

need_ssh() {
    ssh -o ConnectTimeout=10 -o BatchMode=yes "$HOST" true \
        || { echo "ERROR: ssh to $HOST failed (key auth required)"; exit 1; }
}

gen_env() {
    if [ ! -f "$ROOT/docker/.env" ]; then
        echo "== Generating docker/.env with random DB passwords"
        {
            echo "DB_ROOT_PASSWORD=$(openssl rand -hex 12)"
            echo "DB_PASSWORD=$(openssl rand -hex 12)"
            echo "HTTP_PORT=80"
            echo "WITH_PPTX=1"
        } > "$ROOT/docker/.env"
    fi
}

sync_config() {
    gen_env
    DB_PASSWORD="$(grep '^DB_PASSWORD=' "$ROOT/docker/.env" | cut -d= -f2-)"
    echo "== Fetching secrets from production app/config.php"
    # Values are printed by PHP on the server and captured over ssh —
    # the production config file itself is never copied here.
    mapfile -t VALS < <(ssh "$HOST" "php -r '\$c = include \"$REMOTE_APP/app/config.php\"; echo \$c[\"encryption_key\"], PHP_EOL, \$c[\"lang_delete_password\"], PHP_EOL;'")
    ENC_KEY="${VALS[0]:-}"
    LANG_DEL="${VALS[1]:-}"
    if [ -z "$ENC_KEY" ]; then
        echo "ERROR: could not read encryption_key from production"; exit 1
    fi
    cat > "$ROOT/docker/config.container.php" <<PHP
<?php

// GENERATED by tools/offline_sync.sh — git-ignored, do not commit.
// Bind-mounted over app/config.php inside the web container.
// encryption_key matches production so existing passwords and WS tokens work.
return array(
    "db" => array(
        'host' => 'db',
        'login' => 'songs',
        'pass' => '$(php_esc "$DB_PASSWORD")',
        'database' => 'songs',
        'port' => '3306',
    ),
    "encryption_key" => '$(php_esc "$ENC_KEY")',
    "lang_delete_password" => '$(php_esc "$LANG_DEL")',
    "GOOGLE_CLIENT_ID" => "",
    "GOOGLE_CLIENT_SECRET" => "",
);
PHP
    echo "   wrote docker/config.container.php"
}

sync_db() {
    echo "== Dumping production database (credentials stay on the server)"
    ssh "$HOST" 'bash -s' <<'EOF'
set -e
cfg() { php -r '$c = include "/srv/songs/app/config.php"; echo $c["db"]["'"$1"'"];'; }
H=$(cfg host); U=$(cfg login); P=$(cfg pass); D=$(cfg database); PORT=$(cfg port)
# The app connects with host=localhost, i.e. via unix socket — the config
# "port" is not what mysqld listens on. Ask the server the app really talks
# to for its socket path and dump through it; fall back to TCP otherwise.
SOCK=$(php -r '$c = include "/srv/songs/app/config.php"; $m = @new mysqli($c["db"]["host"], $c["db"]["login"], $c["db"]["pass"], $c["db"]["database"]); if ($m->connect_errno) exit(1); echo $m->query("SELECT @@socket s")->fetch_assoc()["s"];' || true)
if [ -n "$SOCK" ]; then CONN="--socket=$SOCK"; else CONN="-h$H -P${PORT:-3306}"; fi
# --no-tablespaces: the app user lacks the PROCESS privilege that
# mysqldump >= 5.7.31 wants for tablespace info (which we don't need).
MYSQL_PWD="$P" mysqldump $CONN -u"$U" \
    --single-transaction --routines --triggers --no-tablespaces \
    --default-character-set=utf8mb4 \
    "$D" | gzip -9 > /tmp/songs_offline_dump.sql.gz
ls -lh /tmp/songs_offline_dump.sql.gz
EOF
    mkdir -p "$ROOT/docker/initdb"
    scp "$HOST:/tmp/songs_offline_dump.sql.gz" "$ROOT/docker/initdb/00_production.sql.gz"
    ssh "$HOST" "rm -f /tmp/songs_offline_dump.sql.gz"
    echo "   wrote docker/initdb/00_production.sql.gz"
    echo "   NOTE: imported only on FIRST db start; to re-import:"
    echo "         cd docker && docker compose down -v && docker compose up -d"
}

sync_media() {
    echo "== Syncing media from production (~1.4 GB on first run)"
    mkdir -p "$ROOT/public"
    ssh "$HOST" "tar -czf - -C $REMOTE_APP/public images tech_media sermon_images sermon_videos sermon_slides" \
        | tar -xzf - -C "$ROOT/public"
    echo "   media synced into public/"
}

need_ssh
case "$PART" in
    config) sync_config ;;
    db)     sync_db ;;
    media)  sync_media ;;
    all)    sync_config; sync_db; sync_media ;;
    *)      echo "Usage: tools/offline_sync.sh [all|config|db|media]"; exit 1 ;;
esac
echo "Done."
